abort init if /etc/default/autossh.default not customized

diff --git a/autossh.init b/autossh.init
--- a/autossh.init
+++ b/autossh.init
@@ -45,6 +45,13 @@ function tunnel () { local x="$@"; AUTOSSH_TUNNELS+=( "$x" ); }
 
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+if [ "${AUTOSSH_HOST}" = "user@myserver.com" ]; then
+    echo "error: autossh-init has not been configured to custom setup."
+    echo " Aborting autossh-init autossh script."
+    echo " Edit /etc/default/autossh.default to resolve."
+    exit 1
+fi
+
 # --
 
 [ ! -e "$RUN" ] && { mkdir "$RUN"; chown "$AUTOSSH_USER": "$RUN"; }
